export const GET_CHAT_DATA_REQUEST = 'GET_CHAT_DATA_REQUEST';
export const GET_CHAT_DATA_SUCCESS = 'GET_CHAT_DATA_SUCCESS';
export const GET_CHAT_DATA_FAIL = 'GET_CHAT_DATA_FAIL';

export const SET_CHAT_DATA_REQUEST = 'SET_CHAT_DATA_REQUEST';
export const SET_CHAT_DATA_SUCCESS = 'SET_CHAT_DATA_SUCCESS';
export const SET_CHAT_DATA_FAIL = 'SET_CHAT_DATA_FAIL';

export const SET_CURRENT_CHANNEL_REQUEST = 'SET_CURRENT_CHANNEL_REQUEST';
export const SET_CURRENT_CHANNEL_SUCCESS = 'SET_CURRENT_CHANNEL_SUCCESS';
export const SET_CURRENT_CHANNEL_FAIL = 'SET_CURRENT_CHANNEL_FAIL';
